name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '5 4 * * 2' # once a week on Tuesday

jobs:
  format:
    name: Format
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v1
      - run: CHECK_FORMAT=1 ./format.sh

  legion:
    name: Fuzzer (${{ matrix.os }}, DEBUG=${{ matrix.debug }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-13']
        debug: ['1', '0']
    steps:
      - uses: actions/checkout@v1
      - run: ./test.sh
        env:
          FUZZER_DEBUG: ${{ matrix.debug }}
          FUZZER_INSTALL_DEPS: '1'
          SUDO_COMMAND: sudo
